### ISSUE TITLE
Not easy to integrate with our game made in Unreal 5.1 and 5.2

### ISSUE THREAD

**Issue by mrjimeneprime** [NVIDIAGameWorks/RTXDI#22]
You guys really need to keep up UE5.  I **need** a plugin for UE5.1 and 5.2 since we cannot achieve 60fps with 30 series cards with Lumen GI and Nanite. Dynamic GI, Nanite, 60fps @hardware's native recommended resolution are all **must haves** for our game due to the mechanics we designed and our studio values.  Lumen is currently overhyped in performance and always requires upscaling from a lower resolution which is unacceptable to our standards.  I have seen a lot with RTXDI and it looks very performant compared with Lumen. I believe we could finally achieve 60fps @ hardware native recommended resolution (3060, 6700 XT, A770, for 1080p, 3070 vendor etc for 1440p, 3080 4k etc ). 

But we do not have the proper setup for integrating the RTXDI into unreal ourselves, compiling the nvRTX branch is takes up too much resources, and we do not want to move our project from the source engine to a fork. We do not want to worry about compiling other plugins from other creators just to use them in NvRTX.  It would be MUCH more convenient and **possible** if you guys included updated plugins for 5.1 and 5.2 with the RTXDI package here. We are embracing DXR as the new standard but we need something more performant but as easy to implement at Lumen. Also try to mix lumen reflections with RTXDI if possible.  We need a new GI system asap.

**Comment by ehartNV** [comment]
We support a set of branches of UE5 under the NvRTX banner which integrate support for RTXDI. Note that there really isn't a way to handle this through a plugin, so it is an engine level integration. It is important to note that Lumen handles a lot of things that RTXDI does not handle.  Also, I should point out that the current implementation of RTXDI for UE only supports light actors and Niagara lights, not emissive surfaces. (Emissive surfaces are planned for future updates.)

This is the repo (needs to be part of the Epic UE group on GitHub)
https://github.com/NvRTX/UnrealEngine

We have a support alias for the branch here: (cc'ed above)

***@***.***

________________________________
From: SÓLíD_SNÁKÉ ***@***.***>
Sent: Sunday, June 25, 2023 12:52 PM
To: NVIDIAGameWorks/RTXDI ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [NVIDIAGameWorks/RTXDI] Not easy to integrate with our game made in Unreal 5.1 and 5.2 (Issue #22)


You guys really need to keep up UE5. I need a plugin for UE5.1 and 5.2 since we cannot achieve 60fps with 30 series cards with Lumen GI and Nanite. Dynamic GI, Nanite, 60fps @hardware<https://github.com/hardware> recommended resolution are all must haves for our game due to the mechanics we designed and our studio values. Lumen is currently overhyped in performance and always requires upscaling from a lower resolution which is unacceptable to our standards. I have seen a lot with RTXDI and it looks very performant compared with Lumen. I believe we could finally achieve 60fps @ hardware native recommended resolution (3060, 6700 XT, A770, for 1080p, 3070 vendor etc for 1440p, 3080 4k etc ).

But we do not have the proper setup for integrating the RTXDI into unreal ourselves, compiling the nvRTX branch is takes up too much resources, and we do not want to move our project from the source engine to a fork. We do not want to worry about compiling other plugins from other creators just to use them in NvRTX. It would be MUCH more convenient and possible if you guys included updated plugins for 5.1 and 5.2 with the RTXDI package here. We are embracing DXR as the new standard but we need something more performant but as easy to implement at Lumen. Also try to mix lumen reflections with RTXDI if possible. We need a new GI system asap.

**Comment by mrjimeneprime** [comment]
If you say an engine level integration has to be the way then I understand. Is that why rtxdi-plugin 5.0 was worse than lumens performance?.  I found the newest version of Lumen(5.2) has 35% decrease in performance which is what I found myself comparing to your RTXDI in your example videos.  

I'm taking the decrease in performance up with Epic Games ASAP. 

>  not emissive surfaces

Looking forward to that. I appreciate the vision. 
Luckily I finally (just now -17 hours-)compiled your NvRTX branch, compiling was so slow on a 10600k?  
Well I appreciate the work and building the branch for us non-engine level devs.

**Comment by mrjimeneprime** [comment]
So I tried to open NvRTX and got this error. https://imgur.com/a/9qltTMT

And the NvRTX fork doesn't have an issue page.

**Comment by ehartNV** [comment]
The error suggests something went wrong with your build or maybe you've got conflicting binary components lying around. We do build and package that branch in automation on a continuous basis.

Generally, I'd recommend:
  1. Closing the solution
  2. Running the generate projects batch file
  3. setting the project config to development editor
  4. doing a rebuild on the UE5 target

This just attempts to make sure you don't have an accidental set of mismatched binaries. I see your build time was brutally long (longer than I'd expect), so I understand that this might be inconvenient.

**Comment by mrjimeneprime** [comment]
> Closing the solution
> Running the generate projects batch file
> setting the project config to development editor
> doing a rebuild on the UE5 target

I did those steps the first build, I don't see the point in waiting another 17 hours.

>  build time was brutally long

Only 30 percent of my CPU was being used. Is there a trick to get VS2022 to use 100%? I've looked this up but everyone is always complaining about how VS is using "_too much_" CPU so I get no answers that help situation.  And trying the build NvRTX has been a tedious process so far and I don't even know if the performance gain with RTXDI will be worth it lol. 

Can you confirm NvRTX's RTXDI is more than 30% percent faster than the lumen GI in 5.1?  I watched the examples video and they compared performance with RTXDI on and off. I would like to know performance in the samples with RTXDI vs the same project with Lumen.

**Comment by sawillms** [comment]
Closing as the UE5 plugin is handled as a separate project and I believe further issues with that plugin can be taken up there directly. Please do continue to report additional general RTXDI issues here though.
