### ISSUE TITLE
[Question] About the rtxdi-sample

### ISSUE THREAD

**Issue by trsh** [NVIDIAGameWorks/RTXDI#9]
1) What setting should I use to reduce/avoid the flickering/blinking in the scene (very vivid after moving around)? https://streamable.com/sm7msk
2) Why does RTXGI have seemingly no effect on the scene? I can turn it off and on and nothing changes visually. Both with "Restir direct light" and "Restir direct light + brdf indirect"

**Comment by r2d2Proton** [comment]
I do second what @trsh posted. It is exactly what I am seeing. Overall, the scene is beautiful, and the codebase well done. I would love to help. I am going to look and see if I can track this down.

**Comment by apanteleev** [comment]
The blinking effect on those metal railings is a shortcoming of the ReSTIR algorithm, at least the way it's implemented in the SDK right now. As the surface is specular and not very rough, it's quite difficult to find a relevant light for it. Spatial reuse doesn't work there because the surface is very small on screen, and there's some normal variation too. Temporal reuse does work and it holds on to lights that were successfully found, while new ones do not arrive in a while for the same pixel. That causes the signal to change slowly, which passes through the denoiser. If you move the camera closer to the railing, it will become larger, and the lighting will clear up.

RTXGI should work, there is a very noticeable difference when you toggle it on and off. Make sure that the RTXGI submodule is initialized and cloned correctly, and that the `RTXDI_WITH_RTXGI` CMake variable is set to ON. (Although the related portion of the UI is unavailable when it's not built, so I'm not sure what's going wrong there). Here's the kind of difference you should expect to see - left half is with RTXGI OFF, right one is ON.

![image](https://user-images.githubusercontent.com/11079788/214971531-517e6a6a-e5be-43ae-8a94-4dddbb0f8aac.png)

(Not sure if the RTXGI question is still relevant, it was asked half a year ago... sorry.)

**Comment by trsh** [comment]
@apanteleev yes indeed. This almost fall into the area of necro-posts. But thank you explaining. Nvidia should really improve support on github bug trackers.
